# Generated by Django 2.0.2 on 2018-02-15 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_positive', models.BooleanField()),
                ('time', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('date_uploaded', models.DateTimeField(blank=True)),
                ('views', models.IntegerField(default=0)),
                ('themes', models.ManyToManyField(related_name='videos', to='my_videos.Theme')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('interaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='my_videos.Interaction')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='my_videos.Video')),
            ],
            bases=('my_videos.interaction',),
        ),
        migrations.CreateModel(
            name='Thumb',
            fields=[
                ('interaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='my_videos.Interaction')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbs', to='my_videos.Video')),
            ],
            bases=('my_videos.interaction',),
        ),
    ]
